# -*- coding: utf-8 -*-
"""Hierarchical Clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCF3nBZ4oVccvYYtO3pvnEP7KA129bYh

# **Hierarchical Clustering**

Credit and more on this tutorial:   [Hierarchical Clustering](https://www.youtube.com/watch?v=v7oLMvcxgFY)

For more on hierarchical clustering: [365 Data Science](https://www.youtube.com/watch?v=ijUMKMC4f9I)

### **Import libraries**
"""

# import all necessary packages
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering

"""###  **Create artificial dataset**"""

# create a artificial data using the blood (200 data points)
dataset = make_blobs(n_samples = 200,
                     n_features = 2,
                     centers = 4,
                     cluster_std = 1.6,
                     random_state = 50)

"""### Assign the dataset"""

# output the dataset variable
dataset

# extract the first dataset which is dataset[0]
points = dataset[0]

"""### **Create the Dendogram**"""

# create a dendrogram
dendrogram = sch.dendrogram(sch.linkage(points, method = 'ward'))
plt.title("Dendrogram")
plt.show();

"""### **Scater plot of the scatters**"""

# plot a scatter
plt.scatter(dataset[0][:,0], dataset[0][:,1])
plt.title("The data clusters");

"""### **Perform the acutal clustering**"""

# clustering with the distance metrics
hierarchical_clus = AgglomerativeClustering(n_clusters = 4, affinity = 'euclidean', linkage='ward')

# predict which cluster the points belong to
y_hc = hierarchical_clus.fit_predict(points)

"""### **Visualize the points**"""

# plot and color the clusters
plt.scatter(points[y_hc == 0,0], points[y_hc == 0,1], s = 100, c='cyan')
plt.scatter(points[y_hc == 1,0], points[y_hc == 1,1], s = 100, c='yellow')
plt.scatter(points[y_hc == 2,0], points[y_hc == 2,1], s = 100, c='red')
plt.scatter(points[y_hc == 3,0], points[y_hc == 3,1], s = 100, c='green')

plt.title("The scatter of all the plots")
plt.show();